services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 12279:27017 # Expose MongoDB on the default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: dmlroot # Set the admin username
      MONGO_INITDB_ROOT_PASSWORD: guzelliginbesparaetmez # Set the admin password
    volumes:
      - ./mongo-data:/data/db # Persist MongoDB data
      - ./mongo-config:/data/configdb # Persist MongoDB configuration
      - ./db.dump:/db.dump
      - ./init.sh:/init.sh
    post_start:
#      - command: mongorestore -u dmlroot -p guzelliginbesparaetmez --archive=/db.dump
      - command: ["sh", "-c", "init.sh"]
      - user: root

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local