services:
  sq_core:
    image: golang:1.25-alpine
    container_name: sq_core
    environment:
      DB_URL: localhost:27017
      DB_USERNAME: dmlroot
      DB_PASSWORD: guzelliginbesparaetmez
    ports:
      - 12280:8080
    volumes:
      - ../../SQ-Core:/service
    command:
      - /service/app
    network_mode: host
