services:
  sq_core:
    image: golang:1.25-alpine
    container_name: sq_core
    environment:
      DB_URL: localhost:27017
      DB_USERNAME: dmlroot
      DB_PASSWORD: guzelliginbesparaetmez
      SERVICE_PORT: 12280
    volumes:
      - ../../SQ-Core:/service
    command:
      - /init.sh
    network_mode: host
