services:
  sq_db:
    image: mongo:8.2.3
    container_name: sq_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dmlroot # Set the admin username
      MONGO_INITDB_ROOT_PASSWORD: guzelliginbesparaetmez # Set the admin password
    volumes:
      - ./data:/data # Persist MongoDB data
      - ./post_setup.sh:/docker-entrypoint-initdb.d/post_setup.sh
    network_mode: host
    