services:
  sq_db:
    image: mongo:8.2.3
    container_name: sq_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dmlroot
      MONGO_INITDB_ROOT_PASSWORD: guzelliginbesparaetmez
    volumes:
      - ./data:/data
      - ./post_setup.sh:/docker-entrypoint-initdb.d/post_setup.sh
    network_mode: host
    